import type { FilterQuery } from '@/types/filtering';
import { router } from '@inertiajs/vue3';

/**
 * Requests a CSV export of an index's current search/sort/filter state
 * -- POSTs the same query shape FilterRequestData::fromRequest() reads,
 * so the export matches exactly what's on screen. The actual file is
 * generated by a queued job; this only creates the pending Export row.
 */
export function useExportRequest(resourceType: string, current: FilterQuery) {
    function requestExport() {
        router.post(
            '/admin/exports',
            {
                resource_type: resourceType,
                search: current.search ?? undefined,
                sort: current.sort ?? undefined,
                direction: current.direction,
                filter: current.filters,
            },
            { preserveScroll: true, preserveState: true },
        );
    }

    return { requestExport };
}
