<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * A requested CSV export of one filterable index, generated by a queued
 * job (App\Jobs\GenerateExportJob) and downloaded via a signed,
 * expiring URL -- see TODO.md Phase 7's "Exports" task.
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('exports', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->string('resource_type');

            // Which reseller the export was requested under, for
            // resource types scoped by the ambient TenantContext
            // (klanten, courses, assignments, attempts) -- the queued
            // job has no HTTP request to resolve this from, so it's
            // captured at request time instead. Null for platform-wide
            // resource types (resellers, users, activity).
            $table->foreignId('reseller_id')->nullable()->constrained()->cascadeOnDelete();

            $table->json('filters');
            $table->string('status')->default('pending');
            $table->string('disk')->nullable();
            $table->string('path')->nullable();
            $table->string('failure_reason')->nullable();
            $table->timestamp('expires_at')->nullable();

            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('exports');
    }
};
